### ISSUE TITLE
redux-undo interoperability

### ISSUE THREAD

**Issue by adrianp** [omnidan/redux-ignore#3]
This is probably more a question than a bug, but is there any way to make redux-ignore work with [redux-undo](https://github.com/omnidan/redux-undo)? I've tried using [combineReducers](http://rackt.org/redux/docs/api/combineReducers.html) (I want both the undo and ignore features on the same reducer), but without success.

**Comment by davidkpiano** [comment]
@adrianp Can you please include a [gist](gist.github.com) of your code that is not working?

**Comment by adrianp** [comment]
@davidkpiano You have it here: https://github.com/adrianp/reduxUndo3

I mostly think that this is due to my misunderstanding on Redux in general. If you run my example, you will see that `store.getState().ignore.type` and `store.getState().undo.past` have the expected values (`bogus` action ignored), while `store.getState().undo.present` does not (in `bogus` state).

P.S.: lodash should probably be moved from `devDependencies` to `dependencies` inside `package.json`.

**Comment by davidkpiano** [comment]
@omnidan Lodash dependency moved in this commit: https://github.com/omnidan/redux-ignore/commit/4eaee58a1ee513c79b2a08f1696d0345ccb8fb81 (probably requires version patch bump)

**Comment by adrianp** [comment]
@davidkpiano :+1:

**Comment by davidkpiano** [comment]
@adrianp Here is the solution:

In your example, you essentially have two different stores, called `'ignore'` and `'undo'` (which, by the way, are arbitrary names. You can call the stores whatever you want.) Redux understands these stores as completely separate, and they don't influence each other.

So what you want is something like this:

```js
const store = createStore(combineReducers({
	fooState: undoable(ignoreActions(reducer, (action) => action.type === 'bogus'))
}));
```

Which will give you this result:

```bash
// toggle action
FOO PRESENT: { type: 'two' }
FOO PAST: [ { type: 'one' } ]
---

// bogus action
FOO PRESENT: { type: 'two' }
FOO PAST: [ { type: 'one' }, { type: 'two' } ]
---
```

**Comment by omnidan** [comment]
BTW: This concept is called *reducer composition* (or more general: *[functional composition](http://scott.sauyet.com/Javascript/Talk/Compose/2013-05-22/)*).

Since reducers are just functions, you can easily combine/compose them like that:

```js
undoable(
  ignoreActions(
    recycleState(
      reducer,
      [INIT_ACTION]
    ),
    (action) => action.type === 'bogus'
  )
)
```

It's a very powerful concept.

**Comment by omnidan** [comment]
@adrianp @davidkpiano Thank you so much - I bumped the version to 1.2.1 and released it on npm :smile:

**Comment by adrianp** [comment]
@davidkpiano @omnidan thanks for the explanations, got it to work correctly now.

**Comment by omnidan** [comment]
@adrianp you're welcome - glad it works now! :grin:
